package-lock.json, package.json, src/index.tsx
=> React-Query 설치 및 설정

.husky/pre-commit, package-lock.json, package.json
pre-commit에서 husky와 lint-staged를 추가합니다
- lint-staged: eslint를 통한 lint 검사
=> pre-commit 설정

package-lock.json, package.json, src/index.tsx
- chakra ui 설정 추가
- chakra ui 설정 추가
=> Feature/setting chakra UI

.github/CODEONWERS
=> PR 자동 리뷰어 설정

src/types/index.ts
API 기본데이터의 타입을 설정합니다
추후 커스텀 데이터가 정의되면 수정해야합니다.
=> [타입정의] API 기본데이터의 타입을 정의

.storybook/main.js, package-lock.json, package.json, src/components/base/ChakraText.tsx, src/components/base/Icon.tsx, src/layout/Footer.tsx, src/stories/ChakraText.stories.tsx, src/stories/Footer.stories.tsx, src/stories/Icon.stories.tsx
- Container 가로 길이 : 640px
- Icon 컴포넌트 가로,세로 길이 : 38px
- ChakraText 컴포넌트 폰트 사이즈 : md
- Icon 컴포넌트와 ChakraText 컴포넌트를 만들었습니다.
- Icon 컴포넌트의 가로, 세로는 38px로 설정하였습니다.
- Footer에서 Icon 컴포넌트와 ChkaraText 컴포넌트를 가져와 사용했습니다.
- (그 외) storybook에서 절대경로를 사용할 수 있게 설정하였습니다.
- (그 외) feather-ui, buffer 라이브러리를 추가하였습니다.
- (참고) feather-ui에서 require로 가져올 때, typescript-eslint 문제를 해결 못하여 임시로 에러무시하는 주석을 두었습니다.
- storybook에서 스크린샷으로 가져왔습니다.
=> [Feat] Footer 컴포넌트 구현

package-lock.json, package.json, src/api/channel.ts, src/api/comment.ts, src/api/follow.ts, src/api/like.ts, src/api/message.ts, src/api/notification.ts, src/api/post.ts, src/api/setting.ts, src/api/user.ts, tsconfig.paths.json
axios를 사용한 api 요청함수들을 정의합니다
- 추후 실제로 api를 사용할 때 수정될 수 있습니다
=> [API] axios - api 요청 함수 정의

src/lib/axios.ts, src/lib/localStorage.ts
1. localStorage에서 토큰을 장하고 꺼낼 수 있습니다
2. axios request에 token을 담아 보내는 interceptor를 추가했습니다
=> [토큰저장] LocalStorage에 토큰을 저장,로드 함수 추가

package-lock.json, package.json, src/components/domain/AuthPage/AuthForm.tsx, src/pages/AuthPage.tsx
로그인 회원가입 폼 작성
`react-hook-form`을 이용하여 로그인 회원가입 탭에 따라 서버로 데이터를 보냅니다. (validation 미포함)
스토리북이 없어서 테스트를 하시려면 제 브랜치에서 `/auth` 경로를 붙여서 나오는 폼에서 해야할 것 같습니다. 죄송합니다 ㅜㅜ
=> 로그인 / 회원가입 폼 작성

src/api/user.ts, src/hooks/quries/useGetOnlineUserList.ts, src/hooks/quries/useGetUserList.ts
전체 userList와 접속중인 onlineUserList를 가져오는 hooks을 추가합니다
사용법
```js
const { data : userList } = useGetUserList()
const { data: onlineUserList } = useGetOnlineUserList()
// userList 작업
```
=> [Hooks] user 관련 hooks 추가

src/api/auth.ts
Auth 관련 api함수를 추가합니다
- 로그인
- 인증 유저인지
- 로그아웃
```js
fetchPostLogin(email: string, password: string)  // 로그인
fetchGetAuthUser // 인증된 유저인지
fetchPostLogout // 로그아웃
```
=> [API] Auth 관련 api 함수 추가

tsconfig.paths.json
=> [개발환경] hooks, lib 절대경로 설정

src/components/domain/ChannelPage/ChannelRadio.tsx, src/components/domain/CreateChallengePage/ChallengeChannelRadio.tsx, src/stories/domain/ChannelPage/ChannelRadio.stories.tsx, src/stories/domain/CreateChallengePage/ChallengeChannelRadio.stories.tsx
- Channel 컴포넌트 추가
- Channel Page, CreateChallengePage에 들어가는 채널 Radio 버튼을 생성하였습니다.
- Channel Page
- 기본 바탕 #FFFFFF
- 선택시 #FF7900
- CreateChllengePage
- 기본 바탕 #F4F6F8
- 선택시 #FF7900
- chakra-ui의 Custom Radio 버튼을 이용하여 구현하였습니다.
- 각 페이지에서 공통적으로 사용하면서 prop을 내려 디자인하려했지만 복잡해져서 따로따로 만들었습니다.
=> [Feat] channel component 만들기

.eslintrc.json, src/components/base/DefaultText.tsx, src/components/domain/NotificationPage/Notification.tsx, src/pages/NotificationPage.tsx, src/stories/base/DefaultText.stories.tsx, src/stories/domain/NotificationPage.stories.tsx/Notification.stories.tsx, src/types/index.ts
- Notification 컴포넌트 구현
-  NotificationPage 구현
- Default text 컴포넌트 구현
- Notification 컴포넌트 구현
알림 type에 따라 메시지를 다르게 구현했습니다.
follow / comment / cheer
- 더미데이터를 활용해 NotificationPage 구현
NotificationList 더미데이터를 활용했습니다. 
#각 타입마다 가지고 있는 옵션이 다른 것 같아서 follow 를 가지고 있으면 follow type, comment 를 가지고 있으면 comment type 으로 나눠줬습니다
틀린 것이 있을 수도 있으니 한번 봐주시면 감사하겠습니다.. 
- Default text 컴포넌트 구현
알림이 없을 때, 사용자 검색 결과가 없을 때 등 사용할 곳이 생각보다 많아보여서 Default text를 컴포넌트로 만들었습니다.
search page에서도 이 컴포넌트를 활용할 예정 입니다ㅎㅎ
- 현재 Notification 컴포넌트를 사용하려고 했는데 notification type과 이름이 겹쳐서 page네에서는 NotiComponent로 사용했습니다. 추후 문제가 될까요? 문제가 된다면 Notification 컴포넌트 이름을 바꾸려고 합니다.
- Notification 객체가 실제 api를 통해 받았을 때 어떤 식으로 작동하는지 몰라서 제가 생각한대료..? 분기를 나눠봤는데 맞는 지 모르겠네요.. 한번 확인해주시면 감사할 것 같습니다😊
=> [Feat ] Notification page 구현

src/components/domain/CommentPage/Comment.tsx, src/stories/domain/CommentPage/Comment.stories.tsx
- Comment Page에 들어가는 Comment 컴포넌트 구현
- API 연결시 수정해야하는 부분
- avatarSrc : author.image
- commentAuthor : author.fullName
- commentContent : comment
- commentCreated : createdAt
=> [Feat] Comment 컴포넌트 추가

src/components/domain/CommentPage/CommentInput.tsx, src/stories/domain/CommentPage/CommentInput.stories.tsx
- 댓글 페이지의 댓글 입력 컴포넌트 구현
- 입력하는 길이가 길어줄수록 textarea의 크기 증가
=> [Feat] CommentInput 컴포넌트 구현

src/pages/HomePage.tsx
=> [fix] redirect 주소 정정

src/pages/EditProfilePage.tsx
사용자 프로필 수정 페이지를 만들었습니다.
프로필 사진 변경은 파일 업로드를 통해야 돼서 아직 만들지 않았고 그 외 닉네임 변경, 비밀번호 변경, 로그아웃 버튼을 포함한 폼을 만들었습니다
=> 사용자 프로필 설정 페이지 만들기

src/lib/axios.ts
=> [API] axios 인스턴스 오타수정

src/pages/NotFoundPage.tsx
not found 페이지를 구현했습니다.
not found text를 추가했습니다
=> [feat] notfound page 구현

src/components/base/ChakraInput.tsx, src/layout/InputLayout.tsx, src/pages/SearchUserPage.tsx
- input 레이아웃에 submit event를 추가했습니다.
- input 레이아웃에 submit event를 추가했습니다.
- 쿼리 변화 시 setUserName을 통해서 search 상태를 변화하게 만들었습니다.
=> [Feat] input layout sumbit event 추가

src/App.tsx, src/components/Router/PrivateRoute.tsx, src/components/Router/index.tsx, src/hooks/quries/useNotifications.ts, src/layout/Footer.tsx, src/layout/Header/index.tsx, src/layout/InputLayout.tsx, src/layout/TextLayout.tsx, src/lib/localStorage.ts, src/pages/EditProfilePage.tsx, src/pages/NotificationPage.tsx, src/store/searchInput.ts, src/stories/domain/FollowPage/PageTab.stories.tsx, src/stories/layout/Footer.stories.tsx, src/stories/layout/InputLayout.stories.tsx, src/stories/layout/TextLayout.stories.tsx, src/stories/pages/SearchUserPage.stories.tsx
1. 로그아웃, 비밀번호 변경 로직 구현
2. 라우터 구조적인 형태로 리팩토링
3. 알람 훅 추가 및 알람페이지 연결
=> [라우터] 라우터 리팩토링, 로그아웃 로직 구현

package-lock.json, package.json, src/components/Router/index.tsx, src/index.tsx
react-router-async 라이브러리로 메타태그를 설정합니다
- title 메타태그를 우선적으로 구현
title : React -> Shallenge로 변경되었습니다
파비콘도 설정할 예정입니다.
=> [SEO] 메타 태그 설정

src/components/Router/index.tsx, src/hooks/usePageTitle.ts, src/pages/ChallengePage.tsx, src/pages/ChallengesPage.tsx, src/pages/EditProfilePage.tsx, src/pages/LoginPage.tsx, src/pages/MyProfilePage.tsx, src/pages/NotificationPage.tsx, src/store/pageTitle.ts
각 페이지에 맞는 타이틀을 전역상태로 설정합니다
커스텀훅과 전역상태로 타이틀을 관리합니다
=> [Feat] 페이지 타이틀 

src/components/base/Card/index.tsx, src/components/domain/ChallengesPage/Challenges.tsx, src/components/domain/ProfilePage/UserChallenges.tsx, src/pages/HomePage.tsx, src/stories/Card.stories.tsx
=> fix: 오타 수정

src/components/Provider/AuthProvider.tsx, src/hooks/useAuth.ts, src/pages/MyProfilePage.tsx
useAuth 훅을 리팩토링합니다
콘솔의 오류메시지를 해결합니다
=> [Fix] useAuth Hook 안에서 로그인 유저상태 관리

src/api/user.ts, src/pages/EditProfilePage.tsx
프로필 이미지를 업로드할 수 있습니다
나의 프로필에서 프로필 이미지 업로드 가능
=> [Feat] 프로필 이미지 업로드 추가

src/pages/ChallengePage.tsx, src/pages/CommentPage.tsx
- 목표 상세 페이지에서 CheerUp 로직 수정
- 로그인한 사용자가 CheerUp 못하는 현상 수정
- 댓글 없는 경우 기본멘트 보여주기
=> [Fix] 로그인 여부에 따른 CheerUp 로직 수정

src/components/Router/index.tsx, src/components/domain/ChallengesPage/Challenges.tsx, src/components/domain/ProfilePage/MyChallenges.tsx, src/components/domain/ProfilePage/OtherChallenges.tsx, src/layout/Footer.tsx, src/pages/HomePage.tsx
=> Fix route fix

src/pages/ChallengePage.tsx, src/pages/CommentPage.tsx
- 목표 상세 페이지 응원하기 버튼 알림
- 목표 댓글 페이지 응원하기 버튼 알림
- 알림 메시지 본인에게 가는 오류 현상 수정
- 해당 post 작성자에게 정상적으로 가도록 수정
=> fix: conflict 해결

public/index.html
- 모바일으로 접속하면 유저가 화면을 확대,축소 하지못하도록 합니다
- viewport 메타태그 추가
=> [Feat] 모바일 확대,축소 방지 메타태그 추가

src/pages/ChallengePage.tsx, src/pages/CreateChallengePage.tsx
- 페이지 타이틀을 수정합니다.
- createChallengePage 타이틀 수정 (30일 챌린지만들기로)
- ChallengePage 타이틀 수정 (challengeTitle로)
=> [Fix] 페이지 타이틀 수정

src/api/notification.ts, src/api/user.ts, src/hooks/quries/useGetUserList.ts, src/pages/HomePage.tsx, src/pages/NotificationPage.tsx, src/pages/SearchUserPage.tsx
- SearchUserPage와 notification Page 에서 api 수정
async await 추가해서 데이터만 받아올 수 있도록 수정했습니다. 
follow 페이지는 계진님 pr 합친 후에 작성할 예정입니다.
=> [refactor] fetch api 부분 async await 수정

src/pages/ChallengePage.tsx
- 목표 상세 기능 추가
- 목표 상세 페이지에 진입하여 하단에 추가하였습니다.
- 본인 계정의 목표가 아닌 경우 나타나지 않습니다.
- 목표기간과 무관하게 생성된 직후부터 계속 나타납니다.
- 피그마 디자인에는 삭제버튼이 디자인되어 있지않아 개인 판단으로 디자인하였습니다.
- 디자인적 피드백을 주시면 반영해드리겠습니다.
=> [Feat] challenge 삭제 기능 추가

src/api/user.ts, src/pages/EditProfilePage.tsx, src/pages/MyProfilePage.tsx
- 프로필 이미지 버그 수정
- 
- useMutation으로 프로필 이미지 변경 요청
=> [Refactor] 프로필 이미지 변경

src/App.tsx, src/components/base/Loading.tsx, src/components/domain/HomePage/PostList.tsx, src/index.tsx, src/pages/HomePage.tsx
- react의 suspense 기능을 사용해 비동기 렌더링을 처리합니다.
- 토스의 기술영상이 Suspense를 잘 설명하고 있습니다. 참고바랍니다.
- https://www.youtube.com/watch?v=FvRtoViujGg
=> [Feature] Suspense 적용 

.eslintignore, cypress.config.ts, cypress/e2e/spec.cy.ts, cypress/fixtures/example.json, cypress/support/commands.ts, cypress/support/e2e.ts, package-lock.json, package.json
Cypress 도입
Cypress라는 라이브러리를 이용하여 로그인 페이지 쪽 테스트 코드를 작성했습니다. 로컬 서버를 켜고 `npx cypress open`을 통해 열린 브라우저에서 테스트 코드를 직접 돌려볼 수 있습니다.
작성 내용은
- 빈 값으로 로그인을 시도했을 때
- 잘못된 값으로 로그인을 시도했을 때
- 로그인 성공
과
=> [Feature] Cypress 추가 / 예시 테스트 코드
